const PUMP_SWAP_PROGRAM_ID: &str = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA";
const EVENT_AUTHORITY: &str = "GS4CU59F31iL7aR2Q8zVS8DRrcRnXX1yjQ66TqNVQnaR";
const GLOBAL_CONFIG: &str = "ADyA8hdefvWN2dbGGWFotbzWxrAvLW83WG6QCVXvJKqw";
const PROTOCOL_FEE_RECIPIENT: &str = "9rPYyANsfQZw3DnDmKE3YCQF5E8oD89UXoHn9JFEhJUz";
const PROTOCOL_FEE_RECIPIENT_TOKEN_ACCOUNT: &str = "Bvtgim23rfocUzxVX9j9QFxTbBnH8JZxnaGLCEkXvjKS";
